- name: damask_parse_env
  setup: |
    source /full/path/to/.venv/bin/activate
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: formable_env
  setup: |
    source /full/path/to/.venv/bin/activate
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: defdap_env
  setup: |
    source /full/path/to/.venv/bin/activate
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: damask_env
  setup: |
    module load mpi/intel-18.0/openmpi/4.1.0
    IMG_PATH=/full/path/to/DAMASK-docker-images/damask-grid_3.0.0-alpha7.sif
    export HDF5_USE_FILE_LOCKING=FALSE
  executables:
  - label: damask_grid
    instances:
    - command: singularity run $IMG_PATH
      num_cores: 1
      parallel_mode: null
    - command: mpirun singularity run $IMG_PATH
      num_cores:
        start: 2
        stop: 32
      parallel_mode: null

- name: matlab_env
  setup: |
    module load matlab/module/file/version
    MTEX_DIR=/full/path/to/toolboxes/mtex/mtex-6.0.0
  executables:
  - label: run_mtex
    instances:
    - command: |
          for dir in $(find ${MTEX_DIR} -type d | grep -v -e ".git" -e "@" -e "private"); do MATLABPATH="${dir};${MATLABPATH}"; done
          export MATLABPATH=${MATLABPATH}
          matlab -softwareopengl -singleCompThread -batch "addpath('<<script_dir>>'); <<script_name_no_ext>> <<args>>"
      num_cores: 1
      parallel_mode: null
  - label: compile_mtex
    instances:
    - command: |
        for dir in $(find ${MTEX_DIR} -type d | grep -v -e ".git" -e "@" -e "private" -e "data" -e "makeDoc" -e "templates" -e "nfft_openMP" -e "compatibility/")
        do
          MTEX_INCLUDE="-I ${dir} ${MTEX_INCLUDE}"
        done
        export MTEX_INCLUDE="${MTEX_INCLUDE} -a ${MTEX_DIR}/data -a ${MTEX_DIR}/plotting/plotting_tools/colors.mat"
        mcc -R -singleCompThread -R -softwareopengl -m "<<script_path>>" <<args>> -o matlab_exe ${MTEX_INCLUDE}
      num_cores: 1
      parallel_mode: null
  - label: run_compiled_mtex
    instances:
    - command: |
        export MATLAB_RUNTIME=/full/path/to/matlab/runtime-or-installation
        ./run_matlab_exe.sh ${MATLAB_RUNTIME} <<args>>
      num_cores: 1
      parallel_mode: null

- name: python_env
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores:
        start: 1
        stop: 32
      parallel_mode: null

- name: dream_3D_env
  executables:
  - label: dream_3D_runner
    instances:
    - command: /full/path/to/dream3d/DREAM3D-6.5.171-Linux-x86_64/bin/PipelineRunner
      num_cores: 1
      parallel_mode: null
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores: 1
      parallel_mode: null

- name: cipher_env
  executables:
  - label: cipher
    instances:
    - command: /full/path/to/cipher/bin/cipher.exe --config cipher_input.yaml
      num_cores: 1
      parallel_mode: null

- name: cipher_processing_env
  setup: |
    source /full/path/to/.venv/bin/activate
  executables:
  - label: python_script
    instances:
    - command: python "<<script_path>>" <<args>>
      num_cores: 1
      parallel_mode: null
