name: Benchmark

on:
  workflow_dispatch: # manual invocation
    inputs:
      python:
        description: "Which Pythons to use."
        default: '["3.12"]'
      num_elements:
        description: "How many elements to make in the workflow."
        default: "[1, 10, 100, 1000, 10000]"
      platform:
        description: "Which OS to use."
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'

jobs:
  workflow-benchmark:
    uses: hpcflow/github-support/.github/workflows/benchmark-impl.yml@main
    with:
      executable_name: matflow
      benchmark_make_workflow: ./matflow/data/workflows/tension_DAMASK_Al_N_repeats.yaml
      python: ${{ github.event.inputs.python }}
      num_elements: ${{ github.event.inputs.num_elements }}
      platform: ${{ github.event.inputs.platform }}
      ref: ${{ github.ref }}
