name: Integration Tests
concurrency: integration
on:
  schedule:
  - cron: "20 2 * * *"
  workflow_dispatch:
    inputs:
      python-version2:
        description: The Python versions to use for the test, as a JSON array.
        default: "[3.12]"
  push: {}

jobs:
  matflow-user-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-version || '["3.12"]') }}
        poetry-version: [ "1.4" ]
    steps:
    - name: Checkout matflow
      uses: actions/checkout@v4
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up poetry
      uses: hpcflow/github-support/setup-poetry@main
      timeout-minutes: 5
      with:
        version: ${{ matrix.poetry-version }}
    - name: Cache dependencies
      uses: hpcflow/github-support/init-cache@main
      with:
        name: integration
        version: ${{ matrix.python-version }}
    - name: Install dependencies
      timeout-minutes: 5
      run: |
        poetry install --without dev,pyinstaller
    - name: Create temp_python_env environment descriptor
      id: env
      uses: uomresearchit/actions/instantiate-file@v1
      with:
        value: |
          - name: temp_python_env
            setup: source ${{ github.workspace }}/.venv/bin/activate
            executables:
              - label: python_script
                instances:
                  - command: python <<script_name>> <<args>>
                    num_cores: 1
                    parallel_mode: null
    - name: Create config file
      id: cfg
      uses: uomresearchit/actions/instantiate-file@v1
      with:
        value: |
          config:
            environment_sources:
              - ${{ steps.env.outputs.filename }}
    - name: Checkout user documentation
      uses: actions/checkout@v4
      with:
        repository: LightForm-group/matflow-user-documentation
        path: userdocs
    - name: Hack the path in the file
      run: |
        perl -pi -e 's/$ENV{REPLACE}/$ENV{PWD}/g' *.yaml
      working-directory: userdocs
      env:
        REPLACE: /home/mbexegc2/projects/lightform/matflow-user-documentation
    - name: Run example workflows from user documentation
      run: |
        poetry run matflow config import ${{ steps.cfg.outputs.filename }}
        poetry run matflow go hello.yaml
        poetry run matflow go groups.yaml
        poetry run matflow show
      working-directory: userdocs
      timeout-minutes: 30
