name: Release
concurrency: release

on:
  pull_request_target:
    branches: [main, develop]
    types: [closed]

jobs:
  release:
    uses: hpcflow/github-support/.github/workflows/release-impl.yml@main
    with:
      gh-run-attempt: ${{ github.run_attempt }}
      pr-merged: ${{ github.event.pull_request.merged }}
      pr-title: ${{ github.event.pull_request.title }}
      pr-base-ref: ${{ github.event.pull_request.base.ref }}
      pr-head-ref: ${{ github.event.pull_request.head.ref }}
      pre_release_branch: develop
      release_branch: main
      app_name: MatFlow
      benchmark_make_workflow: ./matflow/data/workflows/tension_DAMASK_Al_N_repeats.yaml
      docs_url_prefix:
      executable_name: matflow
      pyinstaller_dir: pyinstaller
      pypi-url: https://upload.pypi.org/legacy/
      repository: hpcflow/matflow
      version_file: matflow/_version.py
      website_source_org: hpcflow
      website_source_repo: docs.matflow.io
    secrets:
      general-token: ${{ secrets.GITHUB_TOKEN }}
      commit-token: ${{ secrets.HPCFLOW_ACTIONS_TOKEN }}
      pypi-token: ${{ secrets.PYPI }}
      website-token: ${{ secrets.HPCFLOW_ACTIONS_TOKEN }}
    permissions:
      id-token: write
      contents: write
