name: Test pre-python
on:
  workflow_dispatch: # manual invocation
jobs:
  test:
    uses: hpcflow/github-support/.github/workflows/test-pre-python-impl.yml@main
    with:
      ref: ${{ github.ref }}
      head-ref: ${{ github.head_ref }}
      pytest-args: ""
